services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USERNAME}" ]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 80s
  app:
    image: online-x-o
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
    ports:
      - "${HOST_PORT}:8000"
    env_file:
      - .env
volumes:
  local_pgdata:
    external: false